{"name": "test_new_DM[Chrome]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <Tests.test_02-CreateData.Test_Create object at 0x7f8e6aaafb50>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_new_DM(self):\n        self.create = CreateDataPage(self.driver)\n        self.create.dm_new_user(data.new_message)\n>       assert self.create.is_user_displayed()\n\nTests/test_02-CreateData.py:28: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPages/CreateDataPage.py:108: in is_user_displayed\n    return self.is_displayed(self.USER)\nPages/BasePage.py:46: in is_displayed\n    element = WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located(by_locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"83f0ce3acee38f10d7b5c036f0ccfb8f\")>\nmethod = <selenium.webdriver.support.expected_conditions.visibility_of_element_located object at 0x7f8e6aaaf100>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\n/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException"}, "parameters": [{"name": "init_driver", "value": "'Chrome'"}], "start": 1618829808815, "stop": 1618829835641, "uuid": "8d2ae341-1113-4ed1-8c5d-c7e8f5053774", "historyId": "036b6e4c9c1e6d23358797dba118ad73", "testCaseId": "0a1c86734e860ead12f0483bbde4d91f", "fullName": "Tests.test_02-CreateData.Test_Create#test_new_DM", "labels": [{"name": "severity", "value": "critical"}, {"name": "tag", "value": "@pytest.mark.usefixtures('init_driver')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_02-CreateData"}, {"name": "subSuite", "value": "Test_Create"}, {"name": "host", "value": "Ishrats-MacBook-Air.local"}, {"name": "thread", "value": "4214-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_02-CreateData"}]}